# -*- coding: utf-8 -*-
"""Copy of yolov8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ug_zqJqPSUqFWS8QnQcig1vxJYZEc167
"""

!pip install ultralytics

from google.colab import drive
drive.mount('/content/drive')

!unzip "/content/drive/MyDrive/dataset.zip" -d /content/

yaml_path = "/content/dataset/data_custom.yaml"

with open(yaml_path, "w") as f:
    f.write("""
train: /content/dataset/train/images
val: /content/dataset/val/images

nc: 2
names: ["hat", "jacket"]
""")

!pip uninstall -y torch torchvision torchaudio

!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

!pip install ultralytics

import torch
print(torch.__version__)
print(torch.cuda.is_available())

from ultralytics import YOLO

# load model
model = YOLO("yolov8m.pt")

# train
model.train(
    data="/content/dataset/data_custom.yaml",
    epochs=100,
    imgsz=640,
    batch=8,
    task="detect"
)

!yolo task=detect mode=predict \
model=/content/runs/detect/train/weights/yolov8m_custom.pt \
show=True \
conf=0.5 \
source=/content/1.jpg

from IPython.display import Image, display

display(Image("/content/runs/detect/predict/1.jpg"))

!yolo task=detect mode=predict \
model=/content/runs/detect/train/weights/yolov8m_custom.pt \
source=/content/construction_workers.mp4 \
conf=0.5 \
save=True

import os

print(os.listdir("/content/runs/detect/predict-2"))

from IPython.display import HTML
from base64 import b64encode

video_path = "/content/runs/detect/predict-2/construction_workers.avi"

mp4 = open(video_path, "rb").read()
data_url = "data:video/avi;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=700 controls>
      <source src="{data_url}" type="video/avi">
</video>
""")